services:
  kafka-1:
    image: apache/kafka:3.7.1
    container_name: kafka-1
    hostname: kafka-1
    ports:
      - "19092:9094"
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    command: >
      bash -c "
      /opt/kafka/bin/kafka-storage.sh format --ignore-formatted -t $$CLUSTER_ID -c /etc/kafka/broker.properties &&
      /opt/kafka/bin/kafka-server-start.sh /etc/kafka/broker.properties
      "
    volumes:
      - kafka_1_data:/var/lib/kafka/data
      - ./kafka/broker1.properties:/etc/kafka/broker.properties:ro
    networks:
      - kafka-net

  kafka-2:
    image: apache/kafka:3.7.1
    container_name: kafka-2
    hostname: kafka-2
    ports:
      - "29092:9094"
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    command: >
      bash -c "
      /opt/kafka/bin/kafka-storage.sh format --ignore-formatted -t $$CLUSTER_ID -c /etc/kafka/broker.properties &&
      /opt/kafka/bin/kafka-server-start.sh /etc/kafka/broker.properties
      "
    volumes:
      - kafka_2_data:/var/lib/kafka/data
      - ./kafka/broker2.properties:/etc/kafka/broker.properties:ro
    networks:
      - kafka-net

  kafka-3:
    image: apache/kafka:3.7.1
    container_name: kafka-3
    hostname: kafka-3
    ports:
      - "39092:9094"
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    command: >
      bash -c "
      /opt/kafka/bin/kafka-storage.sh format --ignore-formatted -t $$CLUSTER_ID -c /etc/kafka/broker.properties &&
      /opt/kafka/bin/kafka-server-start.sh /etc/kafka/broker.properties
      "
    volumes:
      - kafka_3_data:/var/lib/kafka/data
      - ./kafka/broker3.properties:/etc/kafka/broker.properties:ro
    networks:
      - kafka-net

volumes:
  kafka_1_data:
  kafka_2_data:
  kafka_3_data:

networks:
  kafka-net:
    driver: bridge
